x-logging:
  &x-logging
  logging:
    driver: 'json-file'
    options:
      max-file: '1'
      max-size: '10m'
version: '3'

services:
  mariadb:
    image: mariadb:10.7 # fix issues when upgrading using: mysql_upgrade -u root -p
    container_name: appwrite-mariadb
    <<: *x-logging
    restart: unless-stopped
    networks:
      - appwrite
    volumes:
      - appwrite-mariadb:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    command: 'mysqld --innodb-flush-method=fsync'
    ports:
      - 3306:3306
  api:
    restart: always
    build: api
    <<: *x-logging
    environment:
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      JWT_KEY: ${JWT_KEY}
      DB_HOST: ${DB_HOST}
      APPWRITE_KEY: ${APPWRITE_KEY}
      APPWRITE_ENDPOINT: ${APPWRITE_ENDPOINT}
      APPWRITE_IDPROJECT: ${APPWRITE_IDPROJECT}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      MONGODB_URL: ${MONGODB_URL}
      SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN}
      ENVIRONMENT: ${ENVIRONMENT}
      CACHE_DB: ${CACHE_DB}
    networks:
      - appwrite
    ports:
      - 8080:8080
  nginx:
    restart: always
    build: nginx
    <<: *x-logging
    ports:
      - "443:443"
    networks:
      - appwrite
  mongo:
    image: mongo:7.0.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: VjxC2cJlKwdE6Q61
    networks:
      - appwrite
    ports:
      - "27017:27017"
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - appwrite
    volumes:
      - cache:/data

networks:
  appwrite:


volumes:
  appwrite-mariadb:
  cache:
    driver: local

    # compose up -d --no-build --remove-orphans
    # .\gradlew clean build -x test
